name: CI

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  build-image:
    name: 'Build container image'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/bryopsida
      image_name: node-scratch-fips
      push_in_pr: true
